name: calculadora_imc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  froom: ^6.0.0
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  froom_generator: ^6.0.0
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
